#17:Sprint17
valer0n3/java-explore-with-me pull request #3
Opened 2023-03-18 23:53 UTC by valer0n3

2023-03-19 10:29 UTC, AnastasiyaFomkina requested changes

2023-03-19 10:29 UTC, AnastasiyaFomkina commented on statistic/dto/pom.xml
> +            <!--          <plugin>
Нужно удалить весь закомментированный код в pom файлах

2023-03-19 10:29 UTC, AnastasiyaFomkina commented on statistic/stats-server/src/main/java/ru/practicum/controller/StatController.java
> +    public List<GetStatDto> getStatistics(@RequestParam(name = "start", required = true)
По умолчанию все параметры `@RequiredParam` являются обязательными, поэтому можно удалить везде `required = true`

2023-03-19 10:29 UTC, AnastasiyaFomkina commented on statistic/stats-client/src/main/java/ru/practicum/controller/StatClientController.java
> +        return getStatDtoList;
Можно сразу возвращать результат работы функции, а не создавать лишнюю переменную

2023-03-19 10:29 UTC, AnastasiyaFomkina commented on statistic/stats-client/src/main/java/ru/practicum/controller/StatClientController.java
> +        this.webClient = WebClient.create("http://localhost:9090");
Лучше вынести url в `application.properties` и вычитывать значение с помощью `@Value`.
Вот в [этой статье](https://www.codejava.net/frameworks/spring-boot/read-values-from-application-properties-file) можно почитать подробнее и посмотреть примеры.
А еще можно будет сразу [заинжектить в конструктор](https://www.baeldung.com/spring-value-annotation#:~:text=6.%20Using%20%40Value%20With%20Constructor%20Injection)

2023-03-19 10:29 UTC, AnastasiyaFomkina commented on statistic/stats-server/src/main/java/ru/practicum/mapper/StatGetMapper.java
> +    StatGetMapper INSTANCE = Mappers.getMapper(StatGetMapper.class);
Лучше инжектить поле с помощью спринга или получать маппер у нужном месте приложения

2023-03-19 10:29 UTC, AnastasiyaFomkina commented on statistic/stats-server/src/main/java/ru/practicum/mapper/StatMapper.java
> +    StatMapper INSTANCE = Mappers.getMapper(StatMapper.class);
Здесь тоже

2023-03-19 11:58 UTC, valer0n3 commented on statistic/dto/pom.xml
> +            <!--          <plugin>
Исправил.

2023-03-19 12:02 UTC, valer0n3 commented on statistic/stats-server/src/main/java/ru/practicum/controller/StatController.java
> +    public List<GetStatDto> getStatistics(@RequestParam(name = "start", required = true)
required = true удалено.

2023-03-19 12:03 UTC, valer0n3 commented on statistic/stats-client/src/main/java/ru/practicum/controller/StatClientController.java
> +        return getStatDtoList;
Исправлено.

2023-03-19 12:48 UTC, valer0n3 commented on statistic/stats-client/src/main/java/ru/practicum/controller/StatClientController.java
> +        this.webClient = WebClient.create("http://localhost:9090");
URL вынесено в app.prop и сделан инжект в конструктор.

2023-03-19 12:53 UTC, valer0n3 commented on statistic/stats-server/src/main/java/ru/practicum/mapper/StatGetMapper.java
> +    StatGetMapper INSTANCE = Mappers.getMapper(StatGetMapper.class);
Исправлено.

2023-03-19 13:04 UTC, valer0n3 commented on statistic/stats-server/src/main/java/ru/practicum/mapper/StatMapper.java
> +    StatMapper INSTANCE = Mappers.getMapper(StatMapper.class);
Исправлено.

2023-03-20 09:04 UTC, AnastasiyaFomkina approved these changes

2023-03-20 09:08 UTC, merged