#17:Sprint17_Part2
valer0n3/java-explore-with-me pull request #5
Opened 2023-04-01 08:34 UTC by valer0n3

2023-04-02 08:29 UTC, AnastasiyaFomkina requested changes

2023-04-02 08:29 UTC, afomkina commented on docker-compose.yml
> +#      - "9081:9081"
Удали, пожалуйста, весь закомментированный код

2023-04-02 08:29 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/categories/dto/CategoryDto.java
> +@Data
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-04-02 08:29 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/categories/mapper/CategoryMapper.java
> +    PostCategoryDto mapCategoryModelToPostCategoryDto(CategoryModel categoryModel);
Этот и метод на 12 строке не используются, нужно удалить

2023-04-02 08:29 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/categories/model/CategoryModel.java
> +@Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/compilations/service/CompilationService.java
> +    public CompilationDto updateCompilation(Long compId, NewCompilationDto newCompilationDto);
Методы интерфейса по дефолту `public`, явно указывать данный модификатор доступа ненужно

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/enums/EventSortEnum.java
> +public enum EventSortEnum {
Не используется, лучше удалить

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/enums/EventStateEnum.java
> +    public static EventStateEnum checkIfEventStateEnumIsCorrect(String state) {
Метод не используется

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/enums/StateActionEnum.java
> +            throw new EwmServiceUnsupportedStatusEnum(String.format("State action can only be: %s, or %s", StateActionEnum.CANCEL_REVIEW));
Здесь и в строке 19 объявлено два аргумента, а передаешь только один `(%s)`

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/events/controllers/AdminEventController.java
> +                                                @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeStart,
Лучше вынести паттерн в публичные константы и переиспользовать по проекту, а не каждый раз обозначать заново

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/events/mapper/LocationMapper.java
> +    LocationDto mapLocationModelToLocationDto(LocationModel locationModel);
Метод должен использоваться

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/users/mapper/UserMapper.java
> +    PostUserDto mapUserModelToPostUserDto(UserModel userModel);
Методы со строк 12 и 14 не используются

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/pom.xml
> +            <artifactId>lombok</artifactId>
Объявлен дважды, эту зависимость нужно удалить

2023-04-02 08:29 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/compilations/service/CompilationServiceImpl.java
> +        if (newCompilationDto.getEvents() != null) {
_Опционально_
Можно реализовать с помощью mapstruct. Хорошей статьи, как это сделать, найти не удалось, попробую объяснить самостоятельно.
В первую очередь нам нужно объявить сам метод
```
Compilation update(Compilation recipient, @MappingTarget Compilation donor);
```
Аннотация `@MappingTarge`t показывает в какую сущность будут маппится изменения. 
По хорошему, можно вообще сделать метод `void`, так как сущность с `@MappingTarget` и так уже будет содержать все изменения:
```
void update(Compilation recipient, @MappingTarget Compilation donor);
```
Соответственно, нужно научить метод обрабатывать `null`, для этого в настройках маппера, нужно будет добавить параметр `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE`
Тогда получатся следующие настройки маппера:
```
@Mapper(
    componentModel = "spring",
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
```
После всех доработок, нужно будет перегенерить проект и можно будет пользоваться сгенерированным методм

2023-04-02 12:54 UTC, valer0n3 commented on docker-compose.yml
> +#      - "9081:9081"
удалил #. Порт 9081 использовал для того, чтобы использовать дебаг в idea, запуская приложение в докере. Если можно, я его оставлю.

2023-04-02 13:05 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/categories/dto/CategoryDto.java
> +@Data
Спасибо за статью. Везде убрал @Data и поставил @Getter, @Setter.

2023-04-02 13:06 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/categories/mapper/CategoryMapper.java
> +    PostCategoryDto mapCategoryModelToPostCategoryDto(CategoryModel categoryModel);
Удалил неиспользуемые методы.

2023-04-02 13:07 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/categories/model/CategoryModel.java
> +@Data
Спасибо за статью. Поправил во всем проекте.

2023-04-02 13:13 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/compilations/service/CompilationService.java
> +    public CompilationDto updateCompilation(Long compId, NewCompilationDto newCompilationDto);
Исправил.

2023-04-02 13:32 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/events/controllers/AdminEventController.java
> +                                                @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeStart,
Исправил во всем проекте

2023-04-02 13:46 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/events/mapper/LocationMapper.java
> +    LocationDto mapLocationModelToLocationDto(LocationModel locationModel);
удалил.

2023-04-02 13:46 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/users/mapper/UserMapper.java
> +    PostUserDto mapUserModelToPostUserDto(UserModel userModel);
Удалил.

2023-04-02 13:50 UTC, valer0n3 commented on ewm-service/pom.xml
> +            <artifactId>lombok</artifactId>
Удалил.

2023-04-02 13:59 UTC, valer0n3 commented on ewm-service/src/main/java/ru/practicum/compilations/service/CompilationServiceImpl.java
> +        if (newCompilationDto.getEvents() != null) {
Большое спасибо за объяснение. Постараюсь это реализовать.

2023-04-03 12:11 UTC, AnastasiyaFomkina approved these changes

2023-04-03 12:11 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/enums/StateActionEnum.java
> +            throw new EwmServiceUnsupportedStatusEnum(String.format("State action can only be: %s, or %s", StateActionEnum.CANCEL_REVIEW));
Забыл поправить `"State action can only be: %s, or %s"` тут обявляешь два параметра `(%s)`, а передаешь один: `StateActionEnum.CANCEL_REVIEW`

2023-04-03 12:53 UTC, merged